linters:
  enable:
    - asciicheck
    - bidichk
    - dupl
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - forcetypeassert
    - gochecknoinits
    - goconst
    - goimports
    - goprintffuncname
    - nakedret
    - nilerr
    - prealloc
    - prealloc
    - unconvert
    - unparam
    - wastedassign
    - whitespace
