// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: feed.proto

package feed

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type PMove_Stage int32

const (
	PMove_PRE_PLAYER_MOVE  PMove_Stage = 0
	PMove_POST_PLAYER_MOVE PMove_Stage = 1
)

// Enum value maps for PMove_Stage.
var (
	PMove_Stage_name = map[int32]string{
		0: "PRE_PLAYER_MOVE",
		1: "POST_PLAYER_MOVE",
	}
	PMove_Stage_value = map[string]int32{
		"PRE_PLAYER_MOVE":  0,
		"POST_PLAYER_MOVE": 1,
	}
)

func (x PMove_Stage) Enum() *PMove_Stage {
	p := new(PMove_Stage)
	*p = x
	return p
}

func (x PMove_Stage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PMove_Stage) Descriptor() protoreflect.EnumDescriptor {
	return file_feed_proto_enumTypes[0].Descriptor()
}

func (PMove_Stage) Type() protoreflect.EnumType {
	return &file_feed_proto_enumTypes[0]
}

func (x PMove_Stage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PMove_Stage.Descriptor instead.
func (PMove_Stage) EnumDescriptor() ([]byte, []int) {
	return file_feed_proto_rawDescGZIP(), []int{0, 0}
}

type PMove struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stage        PMove_Stage `protobuf:"varint,1,opt,name=stage,proto3,enum=feed.PMove_Stage" json:"stage,omitempty"`
	Velocity     []float32   `protobuf:"fixed32,2,rep,packed,name=velocity,proto3" json:"velocity,omitempty"`
	Position     []float32   `protobuf:"fixed32,3,rep,packed,name=position,proto3" json:"position,omitempty"`
	Viewangles   []float32   `protobuf:"fixed32,4,rep,packed,name=viewangles,proto3" json:"viewangles,omitempty"`
	Basevelocity []float32   `protobuf:"fixed32,5,rep,packed,name=basevelocity,proto3" json:"basevelocity,omitempty"`
	Fsu          []float32   `protobuf:"fixed32,6,rep,packed,name=fsu,proto3" json:"fsu,omitempty"`
	Punchangles  []float32   `protobuf:"fixed32,7,rep,packed,name=punchangles,proto3" json:"punchangles,omitempty"`
	EntFriction  float32     `protobuf:"fixed32,8,opt,name=entFriction,proto3" json:"entFriction,omitempty"`
	EntGravity   float32     `protobuf:"fixed32,9,opt,name=entGravity,proto3" json:"entGravity,omitempty"`
	FrameTime    uint32      `protobuf:"varint,10,opt,name=frameTime,proto3" json:"frameTime,omitempty"`
	Buttons      uint32      `protobuf:"varint,11,opt,name=buttons,proto3" json:"buttons,omitempty"`
	Onground     bool        `protobuf:"varint,12,opt,name=onground,proto3" json:"onground,omitempty"`
	Flags        uint32      `protobuf:"varint,13,opt,name=flags,proto3" json:"flags,omitempty"`
	Waterlevel   uint32      `protobuf:"varint,14,opt,name=waterlevel,proto3" json:"waterlevel,omitempty"`
	InDuck       bool        `protobuf:"varint,15,opt,name=inDuck,proto3" json:"inDuck,omitempty"`
	Ladder       bool        `protobuf:"varint,16,opt,name=ladder,proto3" json:"ladder,omitempty"`
	Impulse      uint32      `protobuf:"varint,17,opt,name=impulse,proto3" json:"impulse,omitempty"`
}

func (x *PMove) Reset() {
	*x = PMove{}
	if protoimpl.UnsafeEnabled {
		mi := &file_feed_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PMove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PMove) ProtoMessage() {}

func (x *PMove) ProtoReflect() protoreflect.Message {
	mi := &file_feed_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PMove.ProtoReflect.Descriptor instead.
func (*PMove) Descriptor() ([]byte, []int) {
	return file_feed_proto_rawDescGZIP(), []int{0}
}

func (x *PMove) GetStage() PMove_Stage {
	if x != nil {
		return x.Stage
	}
	return PMove_PRE_PLAYER_MOVE
}

func (x *PMove) GetVelocity() []float32 {
	if x != nil {
		return x.Velocity
	}
	return nil
}

func (x *PMove) GetPosition() []float32 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *PMove) GetViewangles() []float32 {
	if x != nil {
		return x.Viewangles
	}
	return nil
}

func (x *PMove) GetBasevelocity() []float32 {
	if x != nil {
		return x.Basevelocity
	}
	return nil
}

func (x *PMove) GetFsu() []float32 {
	if x != nil {
		return x.Fsu
	}
	return nil
}

func (x *PMove) GetPunchangles() []float32 {
	if x != nil {
		return x.Punchangles
	}
	return nil
}

func (x *PMove) GetEntFriction() float32 {
	if x != nil {
		return x.EntFriction
	}
	return 0
}

func (x *PMove) GetEntGravity() float32 {
	if x != nil {
		return x.EntGravity
	}
	return 0
}

func (x *PMove) GetFrameTime() uint32 {
	if x != nil {
		return x.FrameTime
	}
	return 0
}

func (x *PMove) GetButtons() uint32 {
	if x != nil {
		return x.Buttons
	}
	return 0
}

func (x *PMove) GetOnground() bool {
	if x != nil {
		return x.Onground
	}
	return false
}

func (x *PMove) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *PMove) GetWaterlevel() uint32 {
	if x != nil {
		return x.Waterlevel
	}
	return 0
}

func (x *PMove) GetInDuck() bool {
	if x != nil {
		return x.InDuck
	}
	return false
}

func (x *PMove) GetLadder() bool {
	if x != nil {
		return x.Ladder
	}
	return false
}

func (x *PMove) GetImpulse() uint32 {
	if x != nil {
		return x.Impulse
	}
	return 0
}

type Player struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Health float32 `protobuf:"fixed32,1,opt,name=health,proto3" json:"health,omitempty"`
	Armor  float32 `protobuf:"fixed32,2,opt,name=armor,proto3" json:"armor,omitempty"`
}

func (x *Player) Reset() {
	*x = Player{}
	if protoimpl.UnsafeEnabled {
		mi := &file_feed_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_feed_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_feed_proto_rawDescGZIP(), []int{1}
}

func (x *Player) GetHealth() float32 {
	if x != nil {
		return x.Health
	}
	return 0
}

func (x *Player) GetArmor() float32 {
	if x != nil {
		return x.Armor
	}
	return 0
}

type Damage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Damage    float32   `protobuf:"fixed32,1,opt,name=damage,proto3" json:"damage,omitempty"`
	Direction []float32 `protobuf:"fixed32,2,rep,packed,name=direction,proto3" json:"direction,omitempty"`
	Type      uint32    `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *Damage) Reset() {
	*x = Damage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_feed_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Damage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Damage) ProtoMessage() {}

func (x *Damage) ProtoReflect() protoreflect.Message {
	mi := &file_feed_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Damage.ProtoReflect.Descriptor instead.
func (*Damage) Descriptor() ([]byte, []int) {
	return file_feed_proto_rawDescGZIP(), []int{2}
}

func (x *Damage) GetDamage() float32 {
	if x != nil {
		return x.Damage
	}
	return 0
}

func (x *Damage) GetDirection() []float32 {
	if x != nil {
		return x.Direction
	}
	return nil
}

func (x *Damage) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

type Collision struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Normal         []float32 `protobuf:"fixed32,1,rep,packed,name=normal,proto3" json:"normal,omitempty"`
	Distance       float32   `protobuf:"fixed32,2,opt,name=distance,proto3" json:"distance,omitempty"`
	ImpactVelocity []float32 `protobuf:"fixed32,3,rep,packed,name=impactVelocity,proto3" json:"impactVelocity,omitempty"`
}

func (x *Collision) Reset() {
	*x = Collision{}
	if protoimpl.UnsafeEnabled {
		mi := &file_feed_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Collision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Collision) ProtoMessage() {}

func (x *Collision) ProtoReflect() protoreflect.Message {
	mi := &file_feed_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Collision.ProtoReflect.Descriptor instead.
func (*Collision) Descriptor() ([]byte, []int) {
	return file_feed_proto_rawDescGZIP(), []int{3}
}

func (x *Collision) GetNormal() []float32 {
	if x != nil {
		return x.Normal
	}
	return nil
}

func (x *Collision) GetDistance() float32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *Collision) GetImpactVelocity() []float32 {
	if x != nil {
		return x.ImpactVelocity
	}
	return nil
}

var File_feed_proto protoreflect.FileDescriptor

var file_feed_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x66, 0x65, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x66, 0x65,
	0x65, 0x64, 0x22, 0xaa, 0x04, 0x0a, 0x05, 0x50, 0x4d, 0x6f, 0x76, 0x65, 0x12, 0x27, 0x0a, 0x05,
	0x73, 0x74, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x66, 0x65,
	0x65, 0x64, 0x2e, 0x50, 0x4d, 0x6f, 0x76, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x67, 0x65, 0x52, 0x05,
	0x73, 0x74, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x76, 0x65, 0x6c, 0x6f, 0x63, 0x69, 0x74,
	0x79, 0x18, 0x02, 0x20, 0x03, 0x28, 0x02, 0x52, 0x08, 0x76, 0x65, 0x6c, 0x6f, 0x63, 0x69, 0x74,
	0x79, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x02, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a,
	0x0a, 0x76, 0x69, 0x65, 0x77, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x02, 0x52, 0x0a, 0x76, 0x69, 0x65, 0x77, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x73, 0x12, 0x22, 0x0a,
	0x0c, 0x62, 0x61, 0x73, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x63, 0x69, 0x74, 0x79, 0x18, 0x05, 0x20,
	0x03, 0x28, 0x02, 0x52, 0x0c, 0x62, 0x61, 0x73, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x63, 0x69, 0x74,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x66, 0x73, 0x75, 0x18, 0x06, 0x20, 0x03, 0x28, 0x02, 0x52, 0x03,
	0x66, 0x73, 0x75, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x75, 0x6e, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x6c,
	0x65, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x02, 0x52, 0x0b, 0x70, 0x75, 0x6e, 0x63, 0x68, 0x61,
	0x6e, 0x67, 0x6c, 0x65, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x65, 0x6e, 0x74, 0x46, 0x72, 0x69, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0b, 0x65, 0x6e, 0x74, 0x46,
	0x72, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x6e, 0x74, 0x47, 0x72,
	0x61, 0x76, 0x69, 0x74, 0x79, 0x18, 0x09, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0a, 0x65, 0x6e, 0x74,
	0x47, 0x72, 0x61, 0x76, 0x69, 0x74, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x72, 0x61, 0x6d, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x66, 0x72, 0x61, 0x6d,
	0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x73,
	0x18, 0x0b, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x62, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x73, 0x12,
	0x1a, 0x0a, 0x08, 0x6f, 0x6e, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x0c, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x08, 0x6f, 0x6e, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x66,
	0x6c, 0x61, 0x67, 0x73, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x66, 0x6c, 0x61, 0x67,
	0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x77, 0x61, 0x74, 0x65, 0x72, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18,
	0x0e, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x77, 0x61, 0x74, 0x65, 0x72, 0x6c, 0x65, 0x76, 0x65,
	0x6c, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x6e, 0x44, 0x75, 0x63, 0x6b, 0x18, 0x0f, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x06, 0x69, 0x6e, 0x44, 0x75, 0x63, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x61, 0x64,
	0x64, 0x65, 0x72, 0x18, 0x10, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x6c, 0x61, 0x64, 0x64, 0x65,
	0x72, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x6d, 0x70, 0x75, 0x6c, 0x73, 0x65, 0x18, 0x11, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x07, 0x69, 0x6d, 0x70, 0x75, 0x6c, 0x73, 0x65, 0x22, 0x32, 0x0a, 0x05, 0x53,
	0x74, 0x61, 0x67, 0x65, 0x12, 0x13, 0x0a, 0x0f, 0x50, 0x52, 0x45, 0x5f, 0x50, 0x4c, 0x41, 0x59,
	0x45, 0x52, 0x5f, 0x4d, 0x4f, 0x56, 0x45, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x50, 0x4f, 0x53,
	0x54, 0x5f, 0x50, 0x4c, 0x41, 0x59, 0x45, 0x52, 0x5f, 0x4d, 0x4f, 0x56, 0x45, 0x10, 0x01, 0x22,
	0x36, 0x0a, 0x06, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x61,
	0x6c, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x68, 0x65, 0x61, 0x6c, 0x74,
	0x68, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x72, 0x6d, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x05, 0x61, 0x72, 0x6d, 0x6f, 0x72, 0x22, 0x52, 0x0a, 0x06, 0x44, 0x61, 0x6d, 0x61, 0x67,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x61, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x06, 0x64, 0x61, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x69, 0x72,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x03, 0x28, 0x02, 0x52, 0x09, 0x64, 0x69,
	0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x67, 0x0a, 0x09, 0x43,
	0x6f, 0x6c, 0x6c, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x72, 0x6d,
	0x61, 0x6c, 0x18, 0x01, 0x20, 0x03, 0x28, 0x02, 0x52, 0x06, 0x6e, 0x6f, 0x72, 0x6d, 0x61, 0x6c,
	0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x08, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x26, 0x0a, 0x0e,
	0x69, 0x6d, 0x70, 0x61, 0x63, 0x74, 0x56, 0x65, 0x6c, 0x6f, 0x63, 0x69, 0x74, 0x79, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x02, 0x52, 0x0e, 0x69, 0x6d, 0x70, 0x61, 0x63, 0x74, 0x56, 0x65, 0x6c, 0x6f,
	0x63, 0x69, 0x74, 0x79, 0x42, 0x0b, 0x5a, 0x09, 0x66, 0x65, 0x65, 0x64, 0x2f, 0x66, 0x65, 0x65,
	0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_feed_proto_rawDescOnce sync.Once
	file_feed_proto_rawDescData = file_feed_proto_rawDesc
)

func file_feed_proto_rawDescGZIP() []byte {
	file_feed_proto_rawDescOnce.Do(func() {
		file_feed_proto_rawDescData = protoimpl.X.CompressGZIP(file_feed_proto_rawDescData)
	})
	return file_feed_proto_rawDescData
}

var file_feed_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_feed_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_feed_proto_goTypes = []interface{}{
	(PMove_Stage)(0),  // 0: feed.PMove.Stage
	(*PMove)(nil),     // 1: feed.PMove
	(*Player)(nil),    // 2: feed.Player
	(*Damage)(nil),    // 3: feed.Damage
	(*Collision)(nil), // 4: feed.Collision
}
var file_feed_proto_depIdxs = []int32{
	0, // 0: feed.PMove.stage:type_name -> feed.PMove.Stage
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_feed_proto_init() }
func file_feed_proto_init() {
	if File_feed_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_feed_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PMove); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_feed_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Player); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_feed_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Damage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_feed_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Collision); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_feed_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_feed_proto_goTypes,
		DependencyIndexes: file_feed_proto_depIdxs,
		EnumInfos:         file_feed_proto_enumTypes,
		MessageInfos:      file_feed_proto_msgTypes,
	}.Build()
	File_feed_proto = out.File
	file_feed_proto_rawDesc = nil
	file_feed_proto_goTypes = nil
	file_feed_proto_depIdxs = nil
}
