name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *' # Monthly

jobs:
  build:
    runs-on: ubuntu-20.04

    defaults:
      run:
        working-directory: modlib

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Set up MinGW
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x86

    - name: Set up protoc
      uses: arduino/setup-protoc@v1
      with:
        version: '3.x'
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install protoc-gen-go
      run: go install google.golang.org/protobuf/cmd/protoc-gen-go

    - name: Set up capnproto
      run: sudo apt install capnproto

    - name: Install go-capnproto2
      run: go install capnproto.org/go/capnp/v3/capnpc-go

    - name: Put GOBIN in PATH
      run: printf "$(go env GOPATH)/bin\n" >> $GITHUB_PATH

    - name: Generate protobuf and capnproto defs
      run: make schema

    - name: Set up go environment variables
      run: |
        echo "CC=i686-w64-mingw32-gcc" >> $GITHUB_ENV
        echo "CGO_ENABLED=1" >> $GITHUB_ENV
        echo "GOOS=windows" >> $GITHUB_ENV
        echo "GOARCH=386" >> $GITHUB_ENV

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.45
        working-directory: modlib

    - name: Build
      run: make

    - name: Strip binary
      run: strip hlinspect.dll

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: hlinspect
        path: modlib/hlinspect.dll
