name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: modlib

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Set up MinGW
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x86

    - name: Set up protoc
      uses: arduino/setup-protoc@v1
      with:
        version: '3.x'

    - name: Install protoc-gen-go
      run: go install google.golang.org/protobuf/cmd/protoc-gen-go

    - name: Put GOBIN in PATH
      run: printf "$(go env GOPATH)/bin\n" >> $GITHUB_PATH

    - name: Generate protobuf defs
      run: go generate ./...

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.45
        working-directory: modlib
      env:
        CC: i686-w64-mingw32-gcc
        CGO_ENABLED: 1
        GOOS: windows
        GOARCH: 386

    - name: Build
      run: make
      env:
        CC: i686-w64-mingw32-gcc
        CGO_ENABLED: 1
        GOOS: windows
        GOARCH: 386

    - name: Strip binary
      run: strip hlinspect.dll

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: hlinspect
        path: modlib/hlinspect.dll
